version: 2
registries:
  npm-registry-npm-pkg-github-com-navikt-data-catalog-components:
    type: npm-registry
    url: https://npm.pkg.github.com/@navikt/data-catalog-components
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_NAVIKT_DATA_CATALOG_COMPONENTS_TOKEN}}"
  npm-registry-npm-pkg-github-com-deetly-plotly-view:
    type: npm-registry
    url: https://npm.pkg.github.com/@deetly/plotly-view
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_DEETLY_PLOTLY_VIEW_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nav-frontend-toggle-style
    versions:
    - 1.0.2
    - 1.0.3
    - 1.1.1
  - dependency-name: recharts
    versions:
    - 2.0.4
    - 2.0.6
    - 2.0.7
    - 2.0.8
  - dependency-name: nav-frontend-lesmerpanel-style
    versions:
    - 0.0.45
    - 0.0.47
    - 1.0.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: nav-frontend-spinner-style
    versions:
    - 1.0.1
  - dependency-name: nav-frontend-chevron-style
    versions:
    - 1.0.2
    - 1.0.3
  - dependency-name: react-table
    versions:
    - 7.6.3
  - dependency-name: less
    versions:
    - 4.1.0
  registries:
  - npm-registry-npm-pkg-github-com-navikt-data-catalog-components
  - npm-registry-npm-pkg-github-com-deetly-plotly-view
