# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.1'
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests! using yarn as it was CircleCI default
      - run: yarn test
  package:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: build
          paths: ./*
  deploy-dev:
    docker:
      - image: "navikt/deployment-cli:v0.1.7"
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Checkout NAIS config repository
          command: git clone https://github.com/navikt/arxaas-nais-config.git
      # Publish to Dockerhub
      - nais/docker-deploy:
          image: navikt/webarx-poc
      - run:
          name: Create github deployment for dev-fss
          command: deployment-cli deploy create
                     --cluster=dev-fss
                     --repository=navikt/webarx-poc
                     --team=$TEAMNAME
                     --resource=arxaas-nais-config/webarx-poc-nais.yaml
                     --version=$CIRCLE_SHA1
                     --vars=arxaas-nais-config/webarx-poc-dev-placeholders.json

  deploy-prod:
    docker:
      - image: "navikt/deployment-cli:v0.1.7"
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Checkout NAIS config repository
          command: git clone https://github.com/navikt/arxaas-nais-config.git
      - run:
          name: Create github deployment for prod-fss
          command: deployment-cli deploy create
                     --cluster=prod-fss
                     --repository=navikt/webarx-poc
                     --team=$TEAMNAME
                     --resource=arxaas-nais-config/webarx-poc-nais.yaml
                     --version=$CIRCLE_SHA1
                     --vars=arxaas-nais-config/webarx-poc-prod-placeholders.json

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - package:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - deploy-dev:
          requires:
            - build
            - package
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - deploy-prod:
          requires:
            - build
            - package
            - deploy-dev
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
