name: Build Test Release CI

on: [push]

env:
  DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/webarx-poc
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
