name: Distribute and Deploy

on: 
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/webarx-poc
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  build-package-distribute:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: Test
      run: npm test
      
    - name: Generate tag
      run: |
        # Generate docker image tag
        DATE=$(date +%Y-%m-%d)
        GIT_HASH=$(git rev-parse --short HEAD)
        IMAGE_TAG=${DATE}--${GIT_HASH}
        # write current tag to file
        echo $IMAGE_TAG > docker_img_tag
    - name: Upload img_tag
      uses: actions/upload-artifact@v1
      with:
        name: img_tag
        path: docker_img_tag
    - name: Build and Publish to Docker Image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --tag ${DOCKER_IMAGE}:$(cat docker_img_tag.txt) .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${DOCKER_IMAGE}:$(cat docker_img_tag)
