name: Distribute and Deploy

on: 
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/webarx-poc
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: Test
      run: npm test
    
